export { DeviceFrame2D } from './components/device-frame-2d/DeviceFrame2D'
export { FeatureCloseupScene } from './scene-templates/feature-closeup/FeatureCloseupScene'
export { HeroDeviceScene } from './scene-templates/hero-device/HeroDeviceScene'
export { KeywordCardsScene } from './scene-templates/keyword-cards/KeywordCardsScene'
export { registry } from './registry'
